openapi: 3.0.0
info:
  title: Мир климата
  version: 1.0.0
servers:
  - url: /
paths:
  /climate/api/upload:
    post:
      tags:
        - default
      summary: Загрузить фото и получить qr
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /climate/api/images/getimage:
    get:
      tags:
        - default
      summary: Получить информацию по картинке по айди
      parameters:
        - name: id
          in: query
          schema:
            type: integer
          example: '4'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}